### PR TITLE
fixes #165: Guarantee sort order of results

### LINKED ISSUE #165: Wrong order of results
```
<iq id="b74c8082-54a4-4770-b5ef-fa5658665f10:sendIQ" to="mops@mydomain.local" type="set" from="mops@mydomain.local/jsxc-b69642ac"><query xmlns="urn:xmpp:mam:2" queryid="e01b5704-e2dd-488b-a598-2579c81a1019"><x xmlns="jabber:x:data" type="submit"><field type="hidden" var="FORM_TYPE"><value>urn:xmpp:mam:2</value></field><field var="with"><value>admin@mydomain.local</value></field></x><set xmlns="http://jabber.org/protocol/rsm"><max>20</max><before/></set></query></iq>

<message to="mops@mydomain.local/jsxc-b69642ac"><result xmlns="urn:xmpp:mam:2" queryid="e01b5704-e2dd-488b-a598-2579c81a1019" id="3263"><forwarded xmlns="urn:xmpp:forward:0"><delay xmlns="urn:xmpp:delay" stamp="2021-01-13T20:11:57.372Z"/><message xmlns="jabber:client" id="131f9520-ac13-4cff-b65e-baa8d28c7b90" to="admin@mydomain.local" type="chat" from="mops@mydomain.local/jsxc-99752c3c"><body>F</body><origin-id xmlns="urn:xmpp:sid:0" id="131f9520-ac13-4cff-b65e-baa8d28c7b90"></origin-id><request xmlns="urn:xmpp:receipts"></request><active xmlns="http://jabber.org/protocol/chatstates"></active><markable xmlns="urn:xmpp:chat-markers:0"></markable></message></forwarded></result></message>

<message to="mops@mydomain.local/jsxc-b69642ac"><result xmlns="urn:xmpp:mam:2" queryid="e01b5704-e2dd-488b-a598-2579c81a1019" id="3262"><forwarded xmlns="urn:xmpp:forward:0"><delay xmlns="urn:xmpp:delay" stamp="2021-01-13T20:11:55.759Z"/><message xmlns="jabber:client" id="97b11150-d4d8-4ed3-b5c0-955954d3f91f" to="admin@mydomain.local" type="chat" from="mops@mydomain.local/jsxc-99752c3c"><body>E</body><origin-id xmlns="urn:xmpp:sid:0" id="97b11150-d4d8-4ed3-b5c0-955954d3f91f"></origin-id><request xmlns="urn:xmpp:receipts"></request><active xmlns="http://jabber.org/protocol/chatstates"></active><markable xmlns="urn:xmpp:chat-markers:0"></markable></message></forwarded></result></message>

<message to="mops@mydomain.local/jsxc-b69642ac"><result xmlns="urn:xmpp:mam:2" queryid="e01b5704-e2dd-488b-a598-2579c81a1019" id="3261"><forwarded xmlns="urn:xmpp:forward:0"><delay xmlns="urn:xmpp:delay" stamp="2021-01-13T20:11:54.186Z"/><message xmlns="jabber:client" id="b133b07c-9c8e-4320-99a2-fadff47dd281" to="admin@mydomain.local" type="chat" from="mops@mydomain.local/jsxc-99752c3c"><body>D</body><origin-id xmlns="urn:xmpp:sid:0" id="b133b07c-9c8e-4320-99a2-fadff47dd281"></origin-id><request xmlns="urn:xmpp:receipts"></request><active xmlns="http://jabber.org/protocol/chatstates"></active><markable xmlns="urn:xmpp:chat-markers:0"></markable></message></forwarded></result></message>

<message to="mops@mydomain.local/jsxc-b69642ac"><result xmlns="urn:xmpp:mam:2" queryid="e01b5704-e2dd-488b-a598-2579c81a1019" id="3260"><forwarded xmlns="urn:xmpp:forward:0"><delay xmlns="urn:xmpp:delay" stamp="2021-01-13T20:11:52.670Z"/><message xmlns="jabber:client" id="49b15b84-b6de-4285-b100-01bff702f0ab" to="admin@mydomain.local" type="chat" from="mops@mydomain.local/jsxc-99752c3c"><body>C</body><origin-id xmlns="urn:xmpp:sid:0" id="49b15b84-b6de-4285-b100-01bff702f0ab"></origin-id><request xmlns="urn:xmpp:receipts"></request><active xmlns="http://jabber.org/protocol/chatstates"></active><markable xmlns="urn:xmpp:chat-markers:0"></markable></message></forwarded></result></message>

<message to="mops@mydomain.local/jsxc-b69642ac"><result xmlns="urn:xmpp:mam:2" queryid="e01b5704-e2dd-488b-a598-2579c81a1019" id="3259"><forwarded xmlns="urn:xmpp:forward:0"><delay xmlns="urn:xmpp:delay" stamp="2021-01-13T20:11:51.217Z"/><message xmlns="jabber:client" id="2e9ba264-4f01-4de8-830f-f676b33c7746" to="admin@mydomain.local" type="chat" from="mops@mydomain.local/jsxc-99752c3c"><body>B</body><origin-id xmlns="urn:xmpp:sid:0" id="2e9ba264-4f01-4de8-830f-f676b33c7746"></origin-id><request xmlns="urn:xmpp:receipts"></request><active xmlns="http://jabber.org/protocol/chatstates"></active><markable xmlns="urn:xmpp:chat-markers:0"></markable></message></forwarded></result></message>

<message to="mops@mydomain.local/jsxc-b69642ac"><result xmlns="urn:xmpp:mam:2" queryid="e01b5704-e2dd-488b-a598-2579c81a1019" id="3258"><forwarded xmlns="urn:xmpp:forward:0"><delay xmlns="urn:xmpp:delay" stamp="2021-01-13T20:11:50.371Z"/><message xmlns="jabber:client" id="7ac40b3d-d209-461f-ac02-341414e9d52c" to="admin@mydomain.local" type="chat" from="mops@mydomain.local/jsxc-99752c3c"><body>A</body><origin-id xmlns="urn:xmpp:sid:0" id="7ac40b3d-d209-461f-ac02-341414e9d52c"></origin-id><request xmlns="urn:xmpp:receipts"></request><active xmlns="http://jabber.org/protocol/chatstates"></active><markable xmlns="urn:xmpp:chat-markers:0"></markable></message></forwarded></result></message>

<iq type="result" id="b74c8082-54a4-4770-b5ef-fa5658665f10:sendIQ" from="mops@mydomain.local" to="mops@mydomain.local/jsxc-b69642ac"><fin xmlns="urn:xmpp:mam:2" queryid="e01b5704-e2dd-488b-a598-2579c81a1019"><set xmlns="http://jabber.org/protocol/rsm"><first>3263</first><last>3258</last><count>6</count></set></fin></iq>
```
i noticed the id (3263) in result iq the in "first" is higher than the id (3258) in "last"

`<set xmlns="http://jabber.org/protocol/rsm" > <first>3263</first><last>3258</last><count>6</count></set>`

### PR DESCRIPTION
**Pull request by Fishbowler**
Fixes #165 

[This](https://github.com/igniterealtime/openfire-monitoring-plugin/commit/db634ebc0e1f28fdb835d8f23ef7795baf74fa83) commit, sorting has been reversed whenever a `<before>` is present in a MAM query.
Rather than reintroduce the subquery to enforce the sort, this adds a list sort after retrieving the records.

Presently, this is still an ordering that relies on timestamps (as it always did) but given the granularity of the timestamp, the risks described in [XEP-0313§3.1](https://xmpp.org/extensions/xep-0313.html#archive_order) remain a low probability.

### CODE REVIEW

File: src/java/com/reucon/openfire/plugin/archive/impl/PaginatedMessageDatabaseQuery.java [hunk 1]
```diff
@@ -158,6 +159,7 @@ public String toString()
                 final ArchivedMessage archivedMessage = JdbcPersistenceManager.extractMessage(owner, rs);
                 archivedMessages.add(archivedMessage);
             }
+            archivedMessages.sort(Comparator.comparing(ArchivedMessage::getTime));
```
Comment (guusdk) [inline src/java/com/reucon/openfire/plugin/archive/impl/PaginatedMessageDatabaseQuery.java:162]: Can this be improved by reversing the order of the list, instead of re-ordering it by a property? This probably will have the same result with the current code, but it would keep the responsibility of defining order in one place.

Also, changelog. :)

Comment (Fishbowler) [reply src/java/com/reucon/openfire/plugin/archive/impl/PaginatedMessageDatabaseQuery.java:162]: The results could be in either order when they come out. I'll look at selectively reversing. That would be more performant. And 🤦‍♂️, of course I'll add a change log entry.

Comment (guusdk) [reply src/java/com/reucon/openfire/plugin/archive/impl/PaginatedMessageDatabaseQuery.java:162]: Would it be as simple as evaluating `isPagingBackwards` - or am I missing bits then?

Comment (Fishbowler) [reply src/java/com/reucon/openfire/plugin/archive/impl/PaginatedMessageDatabaseQuery.java]: Turns out: yes. It was exactly that simple.

**Comment by guusdk** [comment]
Thanks Dan!
