### PR TITLE
fix #232 add if clause for sql server

### LINKED ISSUE #232: SQL exception with SQL Server
As reported in https://discourse.igniterealtime.org/t/openfire-messages-are-not-retrieved-4-6-7/

```
com.reucon.openfire.plugin.archive.xep0313.IQQueryHandler - An unexpected exception occurred while processing:
```

```xml
<iq id="af533090-167d-4ef4-b049-42f08b46802c" to="119_98_95_99_104_97_116_105_100_95_49_48_48_49_48_48@conference.openfire.mydomain.ai" type="set" from="pp@openfire.mydomain.ai/9n8xlbdgcj">
   <query xmlns="urn:xmpp:mam:2" queryid="on-initial-load">
      <x xmlns="jabber:x:data" type="submit">
         <field type="hidden" var="FORM_TYPE">
            <value>urn:xmpp:mam:2</value>
         </field>
      </x>
      <set xmlns="http://jabber.org/protocol/rsm">
         <max>100</max>
         <before />
      </set>
      <flip-page />
   </query>
</iq>
```

```
com.reucon.openfire.plugin.archive.impl.DataRetrievalException: com.reucon.openfire.plugin.archive.impl.DataRetrievalException: com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near 'LIMIT'.
    at com.reucon.openfire.plugin.archive.xep0313.IQQueryHandler.retrieveMessages(IQQueryHandler.java:471) ~[?:?]
    at com.reucon.openfire.plugin.archive.xep0313.IQQueryHandler.lambda$handleIQ$2(IQQueryHandler.java:269) ~[?:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_202]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_202]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_202]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_202]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]
````

Totzkotz suggests:
> yes thats seems to be a bug, because Sql Server does not know the "LIMIT" keyword. it uses "TOP" instead...  
some code switches missing here:
1. https://github.com/igniterealtime/openfire-monitoring-plugin/blob/c9b40dd1a1e9bc40b7485068637384fb7ec2c063/src/java/com/reucon/openfire/plugin/archive/impl/PaginatedMucMessageFromOpenfireDatabaseQuery.java#L212
2. https://github.com/igniterealtime/openfire-monitoring-plugin/blob/c9b40dd1a1e9bc40b7485068637384fb7ec2c063/src/java/org/jivesoftware/openfire/archive/ArchiveSearcher.java#L344

### PR DESCRIPTION
**Pull request by mightymop**

### CODE REVIEW

File: src/java/org/jivesoftware/openfire/archive/ArchiveSearcher.java [hunk 1]
```diff
@@ -351,6 +351,11 @@ private Collection<Conversation> databaseSearch(ArchiveSearch search) {
             // rows we need returned. The syntax is LIMIT [rows] OFFSET [offset]
             else if (DbConnectionManager.getDatabaseType() == DbConnectionManager.DatabaseType.postgresql) {
                 query.append(" LIMIT ").append(numResults).append(" OFFSET ").append(startIndex);
+            }
+			// SQL Server optimization: use the OFFSET command to tell the database how many
+            // rows we need returned. The syntax is OFFSET [offset] FETCH NEXT [rows] ROWS ONLY
+			else if (DbConnectionManager.getDatabaseType() == DbConnectionManager.DatabaseType.sqlserver) {
+                query.append(" OFFSET ").append(startIndex).append(" ROWS FETCH NEXT ").append(numResults).append(" ROWS ONLY ");
```
Comment (Fishbowler) [inline src/java/org/jivesoftware/openfire/archive/ArchiveSearcher.java:358]: The syntax doesn't match the comment.

If the code is correct, would line splitting make it more readable?

query
.append(" first "). append (variable)
.appear( " second ".append(variable).append("two")

(Forgive formatting, I'm on mobile which _insists_ I want English rather than Java)

Comment (mightymop) [reply src/java/org/jivesoftware/openfire/archive/ArchiveSearcher.java:358]: doesnt match? why?
startindex = offset and
numResults = count of rows..

so ... OFFSET startIndex ROWS FETCH NEXT numResults ROWS ONLY ... should be correct

**Comment by guusdk** [comment]
Thanks @mightymop !

I've rebased this PR to the current HEAD of the main branch, and I've added a changelog entry.
